version: "3"
services:
    mysql:
        image: "mysql:5.7.28"
        ports:
            - 3306:3306
        restart: unless-stopped
        volumes:
            - ./logs:/var/log/mysql
            - ./data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
